version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: csdfkjlskjlj3490qiu3t
      MYSQL_ONETIME_PASSWORD: "true"
      MYSQL_DATABASE: ccio
      MYSQL_USER: shinobi_user
      MYSQL_PASSWORD: password1234
    volumes:
      - shinobi_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --innodb-buffer-pool-size=1G --innodb-log-buffer-size=128M
    networks:
      - dualstack

  shinobi:
    depends_on:
      - mysql
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - /tank/shinobi/videos:/opt/shinobi/videos
      - /dev/shm/shinobiDockerTemp:/dev/shm/streams
    ports:
      - "8080:8080"
    env_file:
      - ./shinobi.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ccio
      MYSQL_USER: shinobi_user
      MYSQL_PASSWORD: password1234
      utcOffset: "-05:00"
    networks:
      - dualstack

volumes:
  shinobi_mysql: {}

networks:
  dualstack:
    external: true
